### ISSUE TITLE
Where does the data file come from？

### ISSUE THREAD

**Issue by WHYAOAOAO** [fispact/actigamma#5]
Is the data file come from one of the five main evaluated database？Or who  extracted the data and made it into a JSON file？

**Comment by thomasms** [comment]
Good question, and apologies that this is not very transparent.

This data is from the FISPACT-II decay 2012 library (see the decay_2012 here: https://fispact.ukaea.uk/nuclear-data/downloads/). As I recall the decay libraries are a combination of the main evaluated libraries, and some other hand picked additions. They are considered fairly static when compared to the reaction libraries. A more recent version was added, see decay_2020. There are however some notable differences to say the ENDF/B-VII libraries.

The answer to the second question is that I (Thomas Stainer) made them into the JSON file using the pypact package (https://github.com/fispact/pypact). This package parses the output file produced from a FISPACT-II PRINTLIB run (https://fispact.ukaea.uk/wiki/Keyword:PRINTLIB).
