### ISSUE TITLE
Another question

### ISSUE THREAD

**Issue by WHYAOAOAO** [fispact/actigamma#6]
Another question:
I think the activities in the example shouble be called “the numbers of nuclide” rather than “the activitities”.Could you help me about this question?

**Comment by thomasms** [comment]
Sorry, I don't fully understand the question. Could you perhaps point me to the example you're referring to?

**Comment by WHYAOAOAO** [comment]
Define the inventory via activities (or convert from atoms if need be).
# define my unstable inventory by activities (Bq)
inv = ag.UnstablesInventory(data=[
    (db.getzai("Co60"), 9.87e13),
    (db.getzai("Pu238"), 4.e3),
    (db.getzai("U235"), 5.4e8)
])


What meaning are the numbers “9.87e13、4.e3、5.4e8”  ？
“the numbers of nuclide” or “the activities（Bq）”？

**Comment by thomasms** [comment]
These are activities not number of atoms. The main requirement when making this package was to take activities and produce a gamma spec. It is quite trivial to get the activities given the number of atoms using the function here: https://github.com/fispact/actigamma/blob/master/actigamma/core.py#L307.

Feel free to make a similar interface for number of atoms here. That would be greatly appreciated.
